controller_manager:
  ros__parameters:
    update_rate: 100

joint_state_broadcaster:
  type: joint_state_broadcaster/JointStateBroadcaster

diff_drive_controller:
  ros__parameters:
    type: diff_drive_controller/diff_drive_controller

    left_wheel_names: ["Revolute 4"]
    right_wheel_names: ["Revolute 5"]
    wheel_separation: 0.02
    wheel_radius: 0.0065  
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0
    
    #publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Velocity command timeout
    cmd_vel_timeout: 0.5
    
    # Velocity limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.5
        has_acceleration_limits: true
        max_acceleration: 0.5
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.0
        has_acceleration_limits: true
        max_acceleration: 1.0
    